pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  - master

pr:
  branches:
    exclude:
    - *
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    docker build -t $(dockerId)/$(imageName):$(Build.BuildId)-$(Build.BuildNumber) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName):$(Build.BuildId)-$(Build.BuildNumber)