pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - master
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName):$(Date:yyyy-MM-dd)$(Rev:.r)