pool:
  vmImage: 'Ubuntu 16.04'

pr:
  branches:
    include:
    - master

trigger:
  branches:
    include:
    - master
  
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
- script: dotnet test --configuration $(buildConfiguration) --no-build