pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - master
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)